name: datagenerator component build
on:
  push:
    branches:
      - master
    paths:
    - "datagenerator/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      id: build
      run: |
        chmod +x ./mvnw
        ./mvnw clean install
        mvn talend-component:car -Dtalend.car.output=./target/datagenerator-component.car
        echo "::set-output name=pom_version::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)"
      working-directory: datagenerator

    - name: delete
      uses: ame-yu/action-delete-latest-release@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: release
      uses: softprops/action-gh-release@v1
      with:
         tag_name: ${{ steps.build.outputs.pom_version }}
         files: ./datagenerator/target/datagenerator-component.car
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
